In [2]:
import numpy as np
import scikits.bootstrap as bootstrap

In [5]:


raw_data = np.hstack([np.zeros(369-210), np.ones(210)])

In [6]:
raw_data

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1

In [7]:
np.sum(raw_data)

210.0

In [8]:
bootstrap.ci(raw_data, np.sum)

array([ 190.,  228.])

In [17]:
table = np.array([[369,210,68],[397,73,193]])
data = np.zeros((table[0,0]+table[1,0],3))
data[:table[0,0],0]=1
data[table[0,0]:,0]=2
data[:table[0,1],1]=1
data[:table[0,2],2]=1
data[table[0,0]:table[0,0]+table[1,1],1]=1
data[table[0,0]:table[0,0]+table[1,2],2]=1



In [20]:
for i,row in enumerate(data):
    print(i, row)

0 [ 1.  1.  1.]
1 [ 1.  1.  1.]
2 [ 1.  1.  1.]
3 [ 1.  1.  1.]
4 [ 1.  1.  1.]
5 [ 1.  1.  1.]
6 [ 1.  1.  1.]
7 [ 1.  1.  1.]
8 [ 1.  1.  1.]
9 [ 1.  1.  1.]
10 [ 1.  1.  1.]
11 [ 1.  1.  1.]
12 [ 1.  1.  1.]
13 [ 1.  1.  1.]
14 [ 1.  1.  1.]
15 [ 1.  1.  1.]
16 [ 1.  1.  1.]
17 [ 1.  1.  1.]
18 [ 1.  1.  1.]
19 [ 1.  1.  1.]
20 [ 1.  1.  1.]
21 [ 1.  1.  1.]
22 [ 1.  1.  1.]
23 [ 1.  1.  1.]
24 [ 1.  1.  1.]
25 [ 1.  1.  1.]
26 [ 1.  1.  1.]
27 [ 1.  1.  1.]
28 [ 1.  1.  1.]
29 [ 1.  1.  1.]
30 [ 1.  1.  1.]
31 [ 1.  1.  1.]
32 [ 1.  1.  1.]
33 [ 1.  1.  1.]
34 [ 1.  1.  1.]
35 [ 1.  1.  1.]
36 [ 1.  1.  1.]
37 [ 1.  1.  1.]
38 [ 1.  1.  1.]
39 [ 1.  1.  1.]
40 [ 1.  1.  1.]
41 [ 1.  1.  1.]
42 [ 1.  1.  1.]
43 [ 1.  1.  1.]
44 [ 1.  1.  1.]
45 [ 1.  1.  1.]
46 [ 1.  1.  1.]
47 [ 1.  1.  1.]
48 [ 1.  1.  1.]
49 [ 1.  1.  1.]
50 [ 1.  1.  1.]
51 [ 1.  1.  1.]
52 [ 1.  1.  1.]
53 [ 1.  1.  1.]
54 [ 1.  1.  1.]
55 [ 1.  1.  1.]
56 [ 1.  1.  1.]
57 [ 1.  1.  1.]
58 [ 1.  1.  1.]
59 [ 1.

462 [ 2.  0.  1.]
463 [ 2.  0.  1.]
464 [ 2.  0.  1.]
465 [ 2.  0.  1.]
466 [ 2.  0.  1.]
467 [ 2.  0.  1.]
468 [ 2.  0.  1.]
469 [ 2.  0.  1.]
470 [ 2.  0.  1.]
471 [ 2.  0.  1.]
472 [ 2.  0.  1.]
473 [ 2.  0.  1.]
474 [ 2.  0.  1.]
475 [ 2.  0.  1.]
476 [ 2.  0.  1.]
477 [ 2.  0.  1.]
478 [ 2.  0.  1.]
479 [ 2.  0.  1.]
480 [ 2.  0.  1.]
481 [ 2.  0.  1.]
482 [ 2.  0.  1.]
483 [ 2.  0.  1.]
484 [ 2.  0.  1.]
485 [ 2.  0.  1.]
486 [ 2.  0.  1.]
487 [ 2.  0.  1.]
488 [ 2.  0.  1.]
489 [ 2.  0.  1.]
490 [ 2.  0.  1.]
491 [ 2.  0.  1.]
492 [ 2.  0.  1.]
493 [ 2.  0.  1.]
494 [ 2.  0.  1.]
495 [ 2.  0.  1.]
496 [ 2.  0.  1.]
497 [ 2.  0.  1.]
498 [ 2.  0.  1.]
499 [ 2.  0.  1.]
500 [ 2.  0.  1.]
501 [ 2.  0.  1.]
502 [ 2.  0.  1.]
503 [ 2.  0.  1.]
504 [ 2.  0.  1.]
505 [ 2.  0.  1.]
506 [ 2.  0.  1.]
507 [ 2.  0.  1.]
508 [ 2.  0.  1.]
509 [ 2.  0.  1.]
510 [ 2.  0.  1.]
511 [ 2.  0.  1.]
512 [ 2.  0.  1.]
513 [ 2.  0.  1.]
514 [ 2.  0.  1.]
515 [ 2.  0.  1.]
516 [ 2.  0.  1.]
517 [ 2.  

In [35]:
def perf_index(data):
    oct_oct = np.sum(np.where((data[:,0]==1) & (data[:,1]==1),1,0))
    oct_mch = np.sum(np.where((data[:,0]==1) & (data[:,2]==1),1,0))
    mch_oct = np.sum(np.where((data[:,0]==2) & (data[:,1]==1),1,0))
    mch_mch = np.sum(np.where((data[:,0]==2) & (data[:,2]==1),1,0))
    oct_total = np.sum(np.where((data[:,0]==1), 1, 0))
    mch_total = np.sum(np.where((data[:,0]==1), 1, 0))    
    
    pi_oct = (oct_oct - oct_mch)/(oct_total)
    #pi_oct = (oct_oct - oct_mch)/(oct_oct+oct_mch)
    pi_mch = (mch_mch - mch_oct)/(mch_total)
    #pi_mch = (mch_mch - mch_oct)/(mch_oct+mch_mch)
    
    return (pi_oct + pi_mch)/2
print(perf_index(data))
bootstrap.ci(data, perf_index)

0.355013550136


array([ 0.31564987,  0.398017  ])

In [ ]:
p